name: Deploy to GitHub Pages
env:
    PUBLISH_DIR: PGDevOpsTips.Web/bin/Release/net5.0/publish/wwwroot

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Publish app
      run: dotnet publish -c Release
      
    # Changes the base-tag in index.html from '/' to 'PGDevOpsTips' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to PGDevOpsTips
      run: sed -i 's/<base href="\/" \/>/<base href="\/PGDevOpsTips.Web\/" \/>/g' PGDevOpsTips.Web/bin/Release/net5.0/publish/wwwroot/index.html
    
    #- name: Rewrite base href
    #  uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
     # with:
      #  html_path: ${{ env.PUBLISH_DIR }}/index.html
       # base_href: /PGDevOpsTips.Web/
    
    # Allow files and folders starting with an underscore
    - name: Add .nojekyll file
      run: touch PGDevOpsTips.Web/bin/Release/net5.0/publish/wwwroot/.nojekyll
    
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    
